INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('PHYSICIANS FORMULA INC','TITANIUM DIOXIDE, ZINC OXIDE','gwppqv',1),
	 ('SUPERVALU INC.','DIMETHICONE','tietvl',1),
	 ('Hannaford Brothers Company','Dextromethorphan Hydrobromide, Doxylamine Succinate','ucjrmk',0),
	 ('NATURE REPUBLIC CO., LTD.','Titanium Dioxide, OCTINOXATE, Zinc Oxide','cmhnwd',1),
	 ('ALK-Abello, Inc.','Allergenic Extracts Alum Precipitated','abwcfv',0),
	 ('Preferred Pharmaceuticals, Inc.','Carbidopa and Levodopa','sxrofw',1),
	 ('Janssen Pharmaceuticals, Inc.','Methylphenidate hydrochloride','stoinc',0),
	 ('Rebel Distributors Corp','Hydralazine Hydrochloride','wesuci',0),
	 ('Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC','Carisoprodol','sclxpe',1),
	 ('Nelco Laboratories, Inc.','Pike','slowip',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Good Sense (Geiss, Destin & Dunn, Inc.)','DOCUSATE SODIUM','noisyo',1),
	 ('Rejoice International','Benzalkonium Chloride','hnpatr',0),
	 ('Meijer Distribution Inc','Ibuprofen','mgqejj',1),
	 ('Clinical Solutions Wholesale','hydrochlorothiazide','skaixk',1),
	 ('Deliz Pharmaceutical Corp','DEXTROMETHORPHAN HYDROBROMIDE, GUAIFENESIN','jjbpnc',0),
	 ('Nelco Laboratories, Inc.','Rabbitbush','ivlkyf',0),
	 ('Mylan Pharmaceuticals Inc.','repaglinide','apxiby',1),
	 ('Rite Aid','clotrimazole','wsqeph',0),
	 ('KRAMER NOVIS','dextromethorphan hydrobromide, brompheniramine maleate, phenylephrine hydrochloride','qhpjgn',1),
	 ('Paddock Laboratories, LLC','acetylcysteine','qkqaoz',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('The Hain Celestial Group, Inc.','Sodium Monofluorophosphate','wcmgxy',1),
	 ('CVS Pharmacy','acetaminophen, dextromethorphan hbr, phenylephrine hcl','wkvins',0),
	 ('Cargus International, Inc.','Benzocaine','ddkvrl',1),
	 ('Energizer Personal Care LLC','TITANIUM DIOXIDE, ZINC OXIDE','qwzppv',0),
	 ('Apotheca Company','Carbo animalis, Carbo vegetabilis, Kali bichromicum','ncgmft',1),
	 ('King Bio Inc.','Alumina, Antimonium crudum, Arsenicum album, asarum europaeum, Baptisia tinctoria, Carbolicum acidum, Chininum arsenicosum, Cocculus indicus, Lecithin, Picricum acidum, Pulsatilla, Rhus toxicodendron, Silicea, Sulphur','tawhms',0),
	 ('Schering Corporation','isosorbide mononitrate','xrswla',0),
	 ('Bath & Body Works, Inc.','Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone','dtkdxc',1),
	 ('Teva Pharmaceuticals USA Inc','Zolpidem Tartrate','abvbrj',0),
	 ('Respa Pharmaceuticals, Inc.','Chlorpheniramine Maleate, Codeine Phosphate, Pseudoephedrine Hydrochloride','suvnox',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Physicians Total Care, Inc.','Desoximetasone','ogerzf',1),
	 ('Amgen Inc','darbepoetin alfa','ldzent',1),
	 ('ANIP Acquisition Company','Esterified Estrogens and Methyltestosterone','kosfpj',0),
	 ('DeMoulas Market Basket','ACETAMINOPHEN, DEXTROMETHORPHAN HYDROBROMIDE, PHENYLEPHRINE HYDROCHLORIDE','hbakxt',1),
	 ('Cardinal Health','Zolpidem tartrate','cqhpdq',0),
	 ('Shenzhen Senton Science & Technology Co. Ltd','POLOXAMER 188','prqyvz',0),
	 ('Bath & Body Works, Inc.','Avobenzone, Octinoxate, Octisalate, Oxybenzone','uqiwhi',0),
	 ('Dispensing Solutions, Inc.','pioglitazone hydrochloride','sbtyxu',1),
	 ('Shire US Manufacturing Inc.','guanfacine','xamqmg',0),
	 ('YBK Investment, INC','Mask Pack','fdxgdz',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('MSD Consumer Care, Inc.','Homosalate and Oxybenzone','siwyzm',0),
	 ('Jubilant Cadista Pharmaceuticals Inc.','losartan potassium and hydrochlorothiazide','axwekw',1),
	 ('Energizer Personal Care LLC','AVOBENZONE, OCTOCRYLENE, OXYBENZONE','oanugx',1),
	 ('Eight and Company','Arsenicum album, Avena sativa, Bryonia, Capsicum annuum, Carbo animalis, Carduus marianus, Chelidonium majus, Hepar suis, Kali iodatum, Lapis albus, Radium bromatum, Taraxacum officinale, Thuja occidentalis','nqhvfr',0),
	 ('Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.','Zinc Oxide','wkjivs',1),
	 ('Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.','Dimethicone','avwpzh',0),
	 ('Sexton Weldilng Supply Co., Inc.','OXYGEN','zmwzne',0),
	 ('Forces of Nature','Avena Sativa Flowering Top, Arabica Coffee Bean, Lavandula Angustifolia Flowering Top, Passiflora Incarnata Flowering Top, Piper Methysticum Root, and Valerian','ogwgst',1),
	 ('General Injectables & Vaccines, Inc','Ampicillin Sodium','oyjlkn',1),
	 ('Kroger Company','Miconazole nitrate','rsqgqx',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('L''Oreal USA Products Inc','Ensulizole Octinoxate','tnewng',1),
	 ('Aphena Pharma Solutions - Tennessee, LLC','Bisacodyl','fjqygm',0),
	 ('Mylan Pharmaceuticals Inc.','cimetidine','utpngm',1),
	 ('State of Florida DOH Central Pharmacy','Propranolol Hydrochloride','gbutpt',0),
	 ('Janssen Pharmaceuticals, Inc.','risperidone','wyraoa',1),
	 ('SUPERVALU INC.','Diphenhydramine HCl','elmzdm',0),
	 ('Wal-Mart Stores Inc','Bismuth subsalicylate','pxizaa',1),
	 ('Mission Pharmacal Company','alendronate sodium','hynept',1),
	 ('Kosan Kozmetik Sanayi ve Ticaret A.S.','OCTINOXATE','qdzfal',1),
	 ('Jiangsu Province JianErKang Medical Dressing Co. ,Ltd.','Chloroxylenol','omrcak',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Mutual Pharmaceutical Company, Inc.','Phentermine Hydrochloride','gnqqeq',0),
	 ('Uriel Pharmacy Inc.','Prunus spinosa e summ. 30 Special Order','uziiic',1),
	 ('HyVee Inc','cocoa butter, phenylephrine hcl','wivlki',1),
	 ('Hospira, Inc','Piperacillin and Tazobactam','srmuti',0),
	 ('Gilead Sciences, Inc.','ranolazine','vvgcfh',1),
	 ('McKesson','Nicotine Polacrilex','cocsaa',1),
	 ('The Dial Corporation','Triclosan','upkakg',1),
	 ('Pfizer Laboratories Div Pfizer Inc','Vecuronium Bromide','wyppms',1),
	 ('Uriel Pharmacy Inc.','Parathyreoidea Aurum Special Order','pwilkj',0),
	 ('GOJO Industries, Inc.','ALCOHOL','flrfhq',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Major Pharmaceuticals','Lorazepam','blnoog',1),
	 ('Mylan Institutional Inc.','Amiodarone Hydrochloride','ixkjfk',0),
	 ('H E B','Naproxen sodium','iovzqc',0),
	 ('Procter & Gamble Manufacturing Co.','Pyrithione Zinc','oipqdm',0),
	 ('Mutual Pharmaceutical Company, Inc.','Imipramine Hydrochloride','zxuxed',1),
	 ('REMEDYREPACK INC.','Clopidogrel bisulfate','lybmcd',1),
	 ('Smith & Nephew, Inc.','benzethonium chloride and zinc oxide cream','nhkzxe',0),
	 ('China Ningbo Shangge Cosmetic Technology Corp.','Ethyl Alcohol','xwghdi',0),
	 ('Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC','Nortriptyline Hydrochloride','fctonr',1),
	 ('Fresenius Medical Care North America','Dextrose Monohydrate, Sodium Chloride, Calcium Chloride, Magnesium Chloride, Sodium Lactate','frpjwa',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('ABCO Laboratories, Inc.','Human Chorionic Gonadotropin (HCG), Garcinia Cambogia, Hypothalamus','tzhtcc',0),
	 ('International Labs, Inc.','Lisinopril','tjfrsj',0),
	 ('Cardinal Health','Ezetimibe','euccei',0),
	 ('Amneal-Agila, LLC','Nevirapine','rozrku',0),
	 ('Forces of Nature','CALENDULA OFFICINALIS FLOWERING TOP, GERANIUM MACULATUM ROOT, and Silicon Dioxide','sevgwy',1),
	 ('Nelco Laboratories, Inc.','Bald Cypress','btvico',1),
	 ('Energique, Inc','Echinacea (Angustifolia), Tabebuia impetiginosa, Abies nigra, Lycopodium clavatum, Nux vomica, Phosphorus, Pulsatilla (Vulgaris), Sepia, Skatolum, Canadida albicans,','lpyxlm',0),
	 ('Victor Welding Supply Company','Oxygen','dssikv',0),
	 ('Aphena Pharma Solutions - Tennessee, LLC','ARIPIPRAZOLE','fkalsa',0),
	 ('Golden State Medical Supply, Inc.','doxazosin mesylate','eldekm',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Medline Industries, Inc.','bacitracin zinc','byiqmq',0),
	 ('Cangene bioPharma Inc.','Hepatitis B Immune Globulin (Human)','fngqaj',0),
	 ('Blu Pharmaceuticals, LLC','Lisinopril','anjmlj',1),
	 ('Natural Health Supply','Potassium Cation','pmrjtg',0),
	 ('Church & Dwight Co., Inc.','Benzocaine','jjrixn',0),
	 ('Allergy Laboratories, Inc.','cow milk','nrsagx',0),
	 ('Antigen Laboratories, Inc.','Treatment Set TS330156','nejzvm',1),
	 ('MSD Consumer Care, Inc.','Avobenzone, homosalate, octisalate, octocrylene, and oxybenzone','ozzqow',1),
	 ('Direct RX','Orphenadrine Citrate','qbmqum',1),
	 ('Natural Health Supply','MERCURIC CATION','qwvnmm',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('BIOKEY INC.','cilostazol','syuepz',1),
	 ('Sandoz Inc','Repaglinide','ckaiwt',0),
	 ('Shopko Stores Operating Co., LLC','Avobenzone, Octisalate, Octocrylene','lumxzl',1),
	 ('Hannaford Brothers Company','Acetaminophen, Aspirin, Caffeine','vnmzwp',1),
	 ('Apotheca Company','Wild rose,','mncixu',0),
	 ('Cardinal Health','Alprazolam','ijcrnx',1),
	 ('Rite Aid Corporation','Acetaminophen','amzwng',1),
	 ('Novartis Pharmaceuticals Corporation','Interferon beta-1b','tecuzb',0),
	 ('Nelco Laboratories, Inc.','Western Water Hemp','zjakln',0),
	 ('Tomco-Harwel Industries Inc','Triclosan','zmygoy',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Preferred Pharmaceuticals, Inc','Polyvinyl Alcohol','pikkyh',0),
	 ('Mylan Pharmaceuticals Inc.','pravastatin sodium','hekdus',1),
	 ('H and P Industries, Inc. dba Triad Group','salicylic acid','mgqsgg',1),
	 ('Newton Laboratories, Inc.','Apis mel., Arnica, Bellis, Bryonia, Calendula, Chamomilla, Cinchona, Gelsemium, Hamamelis, Hypericum, Lacticum acidum, Ledum, Phosphorus, Rhus toxicodendron, Ruta, Sarcolacticum ac., Staphysag., Symphytum, Echinacea, Hydrastis','moopsq',1),
	 ('sanofi-aventis U.S. LLC','dolasetron mesylate','tuyckj',1),
	 ('Aphena Pharma Solutions - Tennessee, LLC','Oxazepam','tlfkem',0),
	 ('Chain Drug Consortium, LLC (Premier Value)','Diphenhydramine HCl','ayzieh',1),
	 ('STAT RX USA LLC','TRIAZOLAM','gxaffj',1),
	 ('CVS','MAGNESIUM HYDROXIDE','xkjtcf',1),
	 ('Teva Pharmaceuticals USA Inc','Amiodarone Hydrochloride','tmncna',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('BioActive Nutritional','American Cheese, Blue Cheese, Brie Cheese, Cheddar Cheese, Cottage Cheese, Swiss Cheese, Lac Vaccinum, Goat Milk','ymlxne',1),
	 ('IASO Inc','GLYCERIN','ufwevj',1),
	 ('OrchidPharma Inc','Modafinil','efmyem',1),
	 ('Accord Healthcare Inc.','Clopidogrel bisulphate','cmncbo',1),
	 ('REMEDYREPACK INC.','Promethazine Hydrochloride','fpfguq',1),
	 ('New Horizon Rx Group, LLC','Baclofen','utprpe',0),
	 ('Home Health','SALICYLIC ACID','ngvsfr',0),
	 ('Zydus Pharmaceuticals (USA) Inc.','Promethazine Hydrochloride','dyplnp',1),
	 ('Family Dollar Services Inc','Isopropyl Alcohol','cwctjg',1),
	 ('WALGREEN CO.','Diphenhydramine HCl and Phenylephrine HCl','ehmrir',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('EDWARDS PHARMACEUTICAL, INC.','METHENAMINE, SODIUM PHOSPHATE, MONOBASIC, METHYLENE BLUE, and HYOSCYAMINE SULFATE','tyctit',0),
	 ('Ventura Corporation LTD','Octinoxate and Oxybenzone','btvpea',0),
	 ('Patterson Dental Supply Inc','Sodium Fluoride','mmmgmw',1),
	 ('CSL Behring GmbH','antihemophilic factor/von willebrand factor complex (human)','qrkkpx',0),
	 ('Sandoz Inc','Cefdinir','dvxdsc',0),
	 ('Lannett Company, Inc.','Triamterene and Hydrochlorothiazide','xtevjv',1),
	 ('JAFRA COSMETICS INTERNATIONAL','Avobenzone, Octinoxate, Octisalate, Oxybenzone','jcnjlw',0),
	 ('American Health Packaging','Chlorpromazine Hydrochloride','qnmwot',1),
	 ('Cadila Healthcare Limited','Promethazine Hydrochloride','kylbls',0),
	 ('REMEDYREPACK INC.','Fluconazole','tckpqy',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('H.E.B','Bismuth Subsalicylate','ahxfgz',1),
	 ('Kraft Foods Global, Inc.','Menthol','rvaahw',0),
	 ('Target Corporation','Acetaminophen, Caffeine','glkbof',0),
	 ('Bayer HealthCare LLC, Consumer Care','Acetaminophen, Dextromethorphan hydrobromide, chlorpheniramine maleate, and pseudoephedrine Hydrochloride','zuqyfk',1),
	 ('Golden Sun DBA Newhall Laboratories','Salicylic Acid','fnlggi',1),
	 ('Premier Brands of America Inc.','Antifungal Miconazole Powder Jock Itch Spray','ltnutk',1),
	 ('Omorovicza Kozmetikai Kft.','Titanium Dioxide and Zinc Oxide','sdrphr',0),
	 ('A-S Medication Solutions LLC','Metoclopramide','ebkfrf',0),
	 ('Nelco Laboratories, Inc.','Iceberg Lettuce','rhrhbd',0),
	 ('REMEDYREPACK INC.','Ibuprofen','rrmedi',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Atlantic Biologicals Corps','Diazepam','xzieki',0),
	 ('Uriel Pharmacy Inc.','Meteoric Iron Prunus','wvatmq',0),
	 ('Apotheca Company','Aconitum napellus,','lfjtzf',1),
	 ('Procter & Gamble Manufacturing Company','Aluminum Zirconium Trichlorohydrex Gly','xgtwgr',0),
	 ('ALK-Abello, Inc.','White Birch','nlwcmm',1),
	 ('Antigen Laboratories, Inc.','Birch Mixture','bfcmbq',0),
	 ('McKesson','Loratadine','swttcg',1),
	 ('Sandoz Inc.','Phenylephrine Hydrochloride','rpkrad',0),
	 ('Ranbaxy Pharmaceuticals Inc','amlodipine besylate and atorvastatin calcium','mufwme',0),
	 ('Allergy Laboratories, Inc.','anser anser feather','vyrvuz',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('TEVA Pharmaceuticals USA Inc.','Diltiazem Hydrochloride','gwihab',1),
	 ('REMEDYREPACK INC.','Erythromycin','ktgraa',1),
	 ('Teva Pharmaceuticals USA Inc','Glimepiride','akiupm',0),
	 ('Heritage Pharmaceuticals Inc.','Nifedipine','nwvhpx',1),
	 ('Rebel Distributors Corp.','Dicyclomine','mwqjys',1),
	 ('State of Florida DOH Central Pharmacy','minoxidil','zatrul',1),
	 ('Physician Therapeutics LLC','NAPROXEN, .GAMMA.-AMINOBUTYRIC ACID','qhqvun',0),
	 ('Noven Therapeutics, LLC','estradiol/norethindrone acetate transdermal system','dozvod',1),
	 ('THEFACESHOP CO., LTD.','TITANIUM DIOXIDE','rkunrx',0),
	 ('Parfums Christian Dior','OCTINOXATE, TITANIUM DIOXIDE, OXYBENZONE','uguzzq',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('LUPIN PHARMA','cefixime','epross',1),
	 ('Med-Health Pharma, LLC','Levothyroxine Sodium','jalxry',1),
	 ('Apotheca Company','Arnica montana, Hamamelis virginiana, Rhus toxicodendron,','smrbqo',0),
	 ('Jiangxi Sencen Hygienic Products Co., Ltd.','CHLORHEXIDINE GLUCONATE','omemfp',1),
	 ('Glenmark Generics Inc., USA','Lamotrigine','uiovyj',1),
	 ('West-ward Pharmaceutical Corp.','Diltiazem Hydrochloride','hjljys',0),
	 ('Mycone Dental Supply Co., Inc DBA Keystone Industries and Deepak Products Inc.','Sodium Fluoride','cxsmjf',0),
	 ('Uriel Pharmacy Inc.','Secale Nicotiana','hssfzy',0),
	 ('AB7 Industries','METHYL SALICYLATE','kzmqiv',0),
	 ('Allergy Laboratories, Inc.','Festuca elatior pollen','cunxem',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Mylan Institutional Inc.','amlodipine besylate','xzolma',0),
	 ('L''Oreal USA Products Inc','Avobenzone, Homosalate, Octisalate and Octocrylene','kibltc',1),
	 ('BioActive Nutritional, Inc.','Serotonin','zhocxa',0),
	 ('Nelco Laboratories, Inc.','Beet','rkwigz',0),
	 ('Colgate-Palmolive Canada','Sodium Fluoride','qihljl',1),
	 ('Valu Merchandisers Company','Famotidine','kcqobo',0),
	 ('CVS Pharmacy','permethrin','zdcowg',0),
	 ('Oceanside Pharmaceuticals','Methoxsalen','mcazpx',1),
	 ('Endo Pharmaceuticals Inc.','oxymorphone hydrochloride','lmggbi',0),
	 ('Teva Pharmaceuticals USA Inc','Doxazosin Mesylate','uvjdfd',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('ALK-Abello, Inc.','Ash Arizona','cbkxxg',1),
	 ('GOJO Industries, Inc','ethyl alcohol','xsoivx',0),
	 ('Procter and Gamble Manufacturing Company','Aluminum Zirconium Trichlorohydrex Gly','ngxzqr',1),
	 ('HealthLink','Alcohol','mdiycl',1),
	 ('Lannett Company, Inc.','Digoxin','mdvuky',0),
	 ('KAISER FOUNDATION HOSPITALS','ARMODAFINIL','fkkbet',0),
	 ('AmerisourceBergen Drug Corporation (Good Neighbor Pharmacy) 24385','Simethicone','xyxmdh',0),
	 ('HANGZHOU MINO DAILY CHEMICALS CO.LTD.','ZINC OXIDE','essxbu',0),
	 ('Cardinal Health','lidocaine hydrochloride anhydrous and epinephrine','ynmvon',0),
	 ('Nelco Laboratories, Inc.','Gerbil Epithelium','orktus',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Acella Pharmaceuticals, LLC','Pyrilamine Maleate and Phenylephrine Hydrochloride','edgyby',0),
	 ('AnazaoHealth Corporation','i 123 MIBG','lekllv',0),
	 ('Be Better Networks','Nicotine Polacrilex','lkwchq',1),
	 ('Ross Healthcare Inc.','FLUORIDE TREATMENT','cvfksa',0),
	 ('Physicians Total Care, Inc.','oxycodone and aspirin','vmsyux',1),
	 ('Laboratoires Clarins S.A.','TITANIUM DIOXIDE','jmnplx',1),
	 ('Bare Escentuals Beauty Inc.','Titanium Dioxide and Zinc Oxide','eamfqt',1),
	 ('Mylan Pharmaceuticals Inc.','Enalapril Maleate','efpyiv',0),
	 ('H & C Oxygen, Inc.','OXYGEN','hzhdgt',1),
	 ('NEW WORLD IMPORTS, INC.','DEXTRAN 70 AND HYDROXYPROPYL METHYLCELLULOSE','yniceq',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Filo America','Triclosan','bbjiqa',1),
	 ('Novartis Consumer Health, Inc.','Brompheniramine maleate, Phenylephrine HCl','zcceze',1),
	 ('Humanwell PuraCap Pharmaceutical (Wuhan), Ltd.','acetaminophen, dextromethorphan hydrobromide, phenylephrine hydrochloride','nwnvoj',1),
	 ('Nelco Laboratories, Inc.','American Elm','mooooc',0),
	 ('Family Wellness','Potassium Nitrate and Sodium Fluoride','afcjrs',0),
	 ('MEGASOL COSMETIC GMBH','GLYCERIN','qokeyp',1),
	 ('H and P Industries, Inc. dba Triad Group','Glycerin','hkjcne',0),
	 ('Nelco Laboratories, Inc.','Pumpkin','tpxnyt',1),
	 ('Enovachem Manufacturing','Lidocaine HCl','fdxtja',1),
	 ('Golden State Medical Supply','Methylphenidate Hydrochloride','evwvyi',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Mckesson','Guaifenesin','remeic',0),
	 ('Golden State Medical Supply, Inc.','FAMCICLOVIR','caizqf',1),
	 ('The Hain Celestial Group, Inc.','Salicylic Acid','wqpfaj',1),
	 ('VALUE MERCHANDISERS COMPANY, INC.','Acetaminophen, Guaifenesin and Phenylephrine HCl','vryjqj',1),
	 ('Target Corporation','FERRIC OXIDE RED','pshghw',0),
	 ('ALK-Abello, Inc.','House Dust','rfsvys',1),
	 ('Heel Inc.','CITRULLUS COLOCYNTHIS FRUIT PULP and PSEUDOGNAPHALIUM OBTUSIFOLIUM and AMMONIUM CHLORIDE and GELSEMIUM SEMPERVIRENS ROOT and TOXICODENDRON PUBESCENS LEAF and ARSENIC TRIOXIDE and MATRICARIA RECUTITA and','gshjhq',1),
	 ('Silarx Pharmaceuticals, Inc','Citalopram Hydrobromide','uuefmw',0),
	 ('Mylan Pharmaceuticals Inc.','Enalapril Maleate','aczcdh',0),
	 ('Coloplast Manufacturing US, LLC','Alcohol','ycjiha',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Torrent Pharmaceuticals Limited','PIOGLITAZONEHYDROCHLORIDE','rftive',0),
	 ('A-S Medication Solutions LLC','orlistat','rwvicb',1),
	 ('Uriel Pharmacy Inc.','Strophanthus Aurum','zqgvxe',0),
	 ('Ventura Corporation LTD.','Octinoxate and Oxybenzone','jovrjk',0),
	 ('Nelco Laboratories, Inc.','Turkey','awhzko',1),
	 ('Nelco Laboratories, Inc.','Salt Grass','uymzrd',1),
	 ('Winthrop U.S.','desipramine hydrochloride','uxisab',1),
	 ('Smith & Nephew, Inc.','ZINC OXIDE','xywlka',0),
	 ('Safeway','Acetaminophen','ojgfzp',0),
	 ('AB7 Industries','METHYL SALICYLATE','osrlew',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Jubilant HollisterStier LLC','Rice, Whole Grain','rdhcnl',0),
	 ('CVS Pharmacy','Nicotine Polacrilex','jtlbko',1),
	 ('Allermed Laboratories, Inc.','Phalaris arundinaceae','cbcrxb',0),
	 ('REMEDYREPACK INC.','Ceftriaxone Sodium','tgptcp',0),
	 ('Carilion Materials Management','Pramipexole Dihydrochloride','ihqmzy',1),
	 ('HOE HIN PAK FAH YEOW MANUFACTORY LTD','CAMPHOR, MENTHOL AND METHYL SALICYLATE','wvznfv',0),
	 ('Geiss, Destin & Dunn, Inc (Goodsense)','Acetaminophen','swvdbb',1),
	 ('Nelco Laboratories, Inc.','Wheat Bran','eisueq',0),
	 ('C.A Pharm Co., Ltd.','Allantoin','lnynso',0),
	 ('Physicians Total Care, Inc.','Clonazepam','gwneyz',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Neutrogena Corporation','Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone','ghqput',1),
	 ('Procter & Gamble Manufacturing Co','Pyrithione Zinc','ijfrzz',0),
	 ('Rogers Pharmacy','Oxygen','uosknf',1),
	 ('Rebel Distributors Corp.','Amoxicillin','ymkpmr',0),
	 ('Barr Laboratories Inc.','Chlordiazepoxide Hydrochloride','ymjliz',1),
	 ('Avon Products, Inc.','Salicylic Acid','pwceyf',0),
	 ('Sanum Kehlbeck GmbH & Co. KG','mycobacterium phlei','idcxrk',0),
	 ('ProPhase Labs, Inc.','Zinc Gluconate','krnzgk',1),
	 ('Ventura Corporation (San Juan, P.R)','Octinoxate, Oxybenzone, and Titanium Dioxide','iuvwji',0),
	 ('Marathon Pharmaceuticals, LLC','ISOPROTERENOL HYDROCHLORIDE','yghtiz',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Valu Merchandisers Company (Best Choice)','DOCUSATE SODIUM','cncsjx',0),
	 ('Dr. Reddy''s Laboratories Limited','Omeprazole','ghzxod',0),
	 ('Physicians Total Care, Inc.','Terazosin Hydrochloride','gjxbpv',1),
	 ('Energique, Inc.','Alfalfa, Avena Sativa, Fucus Vesiculosus, Thyroidinum (Suis), Agate, Cadmium Iodatum, Calcarea Phosphorica, Cuprum Metallicum','lajjeq',1),
	 ('Preferred Pharmaceuticals, Inc.','BENZONATATE','zazkug',1),
	 ('BJWC','Polyethylene Glycol 3350','wpjezc',1),
	 ('SHISEIDO CO., LTD.','Titanium dioxide','ecwyal',1),
	 ('Best Choice','Bismuth Subsalicylate','wfzjkn',0),
	 ('American Health Packaging','Rifampin','bsmczk',0),
	 ('Neutrogena Corporation','Titanium Dioxide','iqweik',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Ventura Corporation LTD.','Titanium Dioxide, Zinc Oxide, and Octinoxate','lkqvkq',1),
	 ('MallyGirl, LLC','Avobenzone, Octinoxate','knzkss',0),
	 ('Rodan and Fields','Octisalate, Avobenzone, Octocrylene, Homosalate','ddfgai',1),
	 ('PharmaDerm a division of Fougera Pharmaceuticals Inc.','oxiconazole nitrate','sblgmr',1),
	 ('Major Pharmaceuticals','calcium carbonate','rrksbh',0),
	 ('Dr. Fresh, Inc.','SODIUM MONOFLUOROPHOSPHATE','vnnpmk',0),
	 ('Supervalu Inc','Acetaminophen, Dextromethorphan HBr, Doxylamine succinate, Phenylephrine HCl','ksuxkc',1),
	 ('REMEDYREPACK INC.','Topiramate','pmvpup',1),
	 ('Preferred Pharmaceuticals, Inc.','Diclofenac Sodium','rjlszz',0),
	 ('Taro Pharmaceuticals U.S.A., Inc.','Fluconazole','ucjisa',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Physicians Total Care, Inc.','Tadalafil','pooiqj',0),
	 ('Mylan Institutional Inc.','trifluoperazine hydrochloride','onlzku',0),
	 ('Merix Pharmaceutical Corp.','Benzalkonium Chloride','ovuqxq',0),
	 ('SAMJOKO SKYBLUE CO., LTD.','SODIUM MONOFLUOROPHOSPHATE','vahkis',1),
	 ('Mylan Pharmaceuticals Inc.','clozapine','itgofm',1),
	 ('Nelco Laboratories, Inc.','Herring','adxdnh',0),
	 ('American Sales Company','Guaifenesin','mlsink',0),
	 ('Depomed, Inc.','gabapentin','aidwjo',1),
	 ('Apotheca Company','Angelica archangelica, Aralia quinquefolia, Cimicifuga racemosa, Hydrastis canadensis, Pulsatilla, Sabina, Sepia, Sulphuricum acidum, Lachesis mutus,','dwemwk',1),
	 ('Allermed Laboratories, Inc.','Blattella germanica','cyzfia',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('State of Florida DOH Central Pharmacy','stavudine','hlchgk',1),
	 ('American Health Packaging','Hydroxyurea','uxyjuu',1),
	 ('Fresenius Medical Care North America','Dextrose Monohydrate, Sodium Chloride, Sodium Lactate, Calcium Chloride, Magnesium Chloride','hrzeay',1),
	 ('Taro Pharmaceuticals U.S.A., Inc.','clobetasol propionate','wibkun',0),
	 ('Midlothian Laboratories','butalbital, acetaminophen and caffeine','flklce',0),
	 ('HOMEOLAB USA INC.','ACETANILIDUM','ounsxi',1),
	 ('Physicians Total Care, Inc.','Celecoxib','gxcvlt',1),
	 ('Rebel Distributors Corp','Venlafaxine Hydrochloride','tydomi',1),
	 ('Cover FX Skin Care, Inc.','OCTOCRYLENE, OCTINOXATE, OXYBENZONE,TITANIUM DIOXIDE','dsxstm',1),
	 ('L Perrigo Company','Simethicone','zplaiq',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Rebel Distributors Corp','Etodolac','jesint',1),
	 ('Circadia by Dr Pugliese, Inc.','Avobenzone, Octinoxate and Octocrylene','ozkxrj',1),
	 ('Pfizer Laboratories Div Pfizer Inc.','Fluorouracil','dlywpa',1),
	 ('NATURE REPUBLIC CO., LTD.','Alcohol','wwqmqd',0),
	 ('Nelco Laboratories, Inc.','Saltbush','jcyvxo',0),
	 ('SDA Laboratories, Inc.','Bismuth Subsalicylate','nnjtfh',1),
	 ('REMEDYREPACK INC.','DIPHENHYDRAMINE HYDROCHLORIDE','yqgsbs',0),
	 ('GOJO Industries, Inc.','ALCOHOL','lsudyc',0),
	 ('Physicians Total Care, Inc.','Bicalutamide','wqiyaq',0),
	 ('WALGREEN CO.','Aspirin','ykkisy',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Hospira, Inc.','METOCLOPRAMIDE HYDROCHLORIDE','bjmhmt',1),
	 ('Sun Pharma Global FZE','Temozolomide','mtypwu',1),
	 ('Meijer Distribution Inc','White Petrolatum','kjygee',0),
	 ('Church & Dwight Co., Inc.','Sodium Fluoride','nitskx',0),
	 ('Bobbi Brown Professional Cosmetics Inc.','OCTINOXATE and TITANIUM DIOXIDE','moqfqf',1),
	 ('REMEDYREPACK INC.','Sulfamethoxazole and Trimethoprim','yzxhiw',1),
	 ('Dolgencorp, LLC','Acetaminophen, Aspirin, Caffeine','gcilhv',1),
	 ('Ventura Corporation LTD.','Octinoxate','etwujk',1),
	 ('Major Pharmaceuticals','Ibuprofen','pjafmh',0),
	 ('Rebel Distributors Corp','clonidine hydrochloride','oflqmt',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Mckesson','acetaminophen, dextromethorphan Hbr, Phenylephrine HCl','sxzaib',0),
	 ('Watson Pharma, Inc.','progesterone','zgixxt',1),
	 ('Jubilant HollisterStier LLC','Ragweed. Western Ambrosia psilostachya','exfnuu',0),
	 ('Procter & Gamble Manufacturing Company','Aluminum Zirconium Trichlorohydrex Gly','mobbij',1),
	 ('Qualitest Pharmaceuticals','Ranitidine','eemzfn',1),
	 ('Ventura Corporation LTD.','Octinoxate and Oxybenzone','irxsjh',0),
	 ('Safeway Inc.','Acetaminophen','mgvrxh',1),
	 ('Vidara Therapeutics Inc','Interferon gamma-1b','tojhqb',1),
	 ('Uriel Pharmacy Inc.','Apis Levisticum','kdqyss',1),
	 ('Rebel Distributors Corp','Venlafaxine Hydrochloride','glvgzr',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Physicians Total Care, Inc.','Morphine Sulfate','eijeec',0),
	 ('Nelco Laboratories, Inc.','Turnip','ijfumy',0),
	 ('Peaceful Mountain, Inc.','Bryonia, Ruta Graveolens, Bellis Perennis, Argentum Metallicum','wjqjfh',0),
	 ('Qualitest Pharmaceuticals','Propafenone Hydrochloride','hwbhfx',0),
	 ('Physicians Total Care, Inc.','Besifloxacin','pxzbrt',1),
	 ('Topical Pharmaceuticals Inc.','Benzalkonium Chloride','pmwdkf',0),
	 ('Par Pharmaceutical Inc.','oxandrolone','nffuvs',1),
	 ('Air Liquide America L.P.','NITROGEN','umukfi',1),
	 ('Cardinal Health','adenosine','vbfkfb',0),
	 ('Hospira, Inc.','GENTAMICIN SULFATE','cabgcj',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('CVS Pharmacy','Ibuprofen','ruaqdc',1),
	 ('Rituals Cosmetics USA, Inc.','TITANIUM DIOXIDE','ixayaw',0),
	 ('REMEDYREPACK INC.','Ceftriaxone Sodium','ovrmlw',0),
	 ('Nartex Laboratories','Passiflora incarnata, Ignatia Amara, Valeriana Officinalis','lflsik',1),
	 ('Purdue Pharma LP','morphine sulfate','vvpdlr',1),
	 ('STAT RX USA LLC','GENTAMICIN SULFATE','zjzmmz',1),
	 ('Prime Packaging, Inc.','Avobenzone, Homosalate, Octisalate, Octocrylene and Oxybenzone','uckdnf',1),
	 ('Allied Pharma Inc','Clarithromycin','pdopzl',0),
	 ('Physicians Total Care, Inc.','rizatriptan benzoate','fweljt',1),
	 ('B. Braun Medical Inc.','DEXTROSE, SODIUM CHLORIDE, and POTASSIUM CHLORIDE','xsrncc',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('The Mentholatum Company','menthol, methyl salicylate','qpuvik',0),
	 ('Active and Innovative','Camphor and Menthol','kymqoy',1),
	 ('Tender Corp dba Adventure Medical Kits','BENZALKONIUM CHLORIDE, BENZOCAINE, SD ALCOHOL, BACITRACIN ZINC, NEOMYCIN SULFATE, POLYMYXIN B, IBUPROFEN, ACETAMINOPHEN','cqjsvi',1),
	 ('Hannaford Brothers Company','Acetaminophen','rkrudi',0),
	 ('WAKEFERN FOOD CORPORATION','Mineral Oil','nwpugt',0),
	 ('L''Oreal USA Florence Manufacturing','Salicylic Acid','saxifo',1),
	 ('REMEDYREPACK INC.','Allopurinol','buchxe',1),
	 ('Sagent Pharmaceuticals','nafcillin sodium','apjzoi',0),
	 ('NATURE REPUBLIC CO., LTD.','Glycerin, Dimethicone','nnqbfz',1),
	 ('Greenstone LLC','quinapril hydrochloride','aarzis',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Laura Geller Beauty, LLC','OCTINOXATE, OCTOCRYLENE, AVOBENZONE','erwuoi',0),
	 ('Syntrion GmbH','PENICILLIUM CHRYSOGENUM VAR. CHRYSOGENUM','wzgdes',1),
	 ('HyVee Inc','famotidine, calcium carbonate and magnesium hydroxide','ogfxtp',0),
	 ('Guthy-Renker LLC','ZINC OXIDE','ptfcnd',1),
	 ('Fred''s Inc.','bacitracin zinc,neomycin sulfate, polymyxin b sulfate, pramoxine hydrochloride','tzljxm',1),
	 ('Mylan Institutional Inc.','clozapine','jdvzdq',0),
	 ('Golden State Medical Supply, Inc.','Warfarin Sodium','ewauit',1),
	 ('Nomax Inc.','Fluorescein Sodium','ynylkh',1),
	 ('Changzhou Jianze Sanitary Material Co., Ltd.','ISOPROPYL ALCOHOL','sbdhbt',1),
	 ('Fischer Pharmaceuticals Ltd.','Avobenzone, Octinoxate, Octisalate, Octocrylene, Oxybenzone','hswzzx',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('L. Perrigo Company','dextromethorphan polistirex','jjvrha',0),
	 ('Preferred Pharmaceuticals, Inc.','erythromycin','gqhfzp',1),
	 ('GlaxoSmithKline Consumer Healthcare LP','sodium fluoride','nvxjjx',0),
	 ('Physicians Total Care, Inc.','tolterodine tartrate','rnzzhm',1),
	 ('Health Care Products','undecylenic acid','nyvfgo',1),
	 ('Actient Pharmaceuticals, LLC','alprostadil','xurght',0),
	 ('Kmart Corporation','FERRIC OXIDE RED','eghenj',0),
	 ('SJ Creations, Inc.','Triclosan','fnbgmu',0),
	 ('Antigen Laboratories, Inc.','Stemphylium','wfpimz',0),
	 ('WALGREEN CO.','BISMUTH SUBSALICYLATE','vxzzui',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Novartis Consumer Health, Inc.','Acetaminophen, Aspirin (NSAID) and Caffeine','cinwxh',1),
	 ('ESTEE LAUDER INC','Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone','jrwkuj',0),
	 ('Hy-Vee','Acetaminophen, Aspirin, Caffeine','qxgqbs',1),
	 ('Stat Rx USA','Diclofenac Sodium','ievxei',1),
	 ('Supervalu Inc','Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl','jvrkoo',0),
	 ('REMEDYREPACK INC.','Sulfamethoxazole and Trimethoprim','owcrrs',0),
	 ('Apotex Corporation','CEFOXITIN','jjjwtw',0),
	 ('Dolgencorp, LLC','Acetaminophen','ryfkiz',1),
	 ('Northwind Pharmaceuticals','Atorvastatin Calcium','smextu',1),
	 ('Teva Pharmaceuticals USA Inc','Lorazepam','fhzquq',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Ranbaxy Pharmaceuticals Inc','Pioglitazone','sjwltp',0),
	 ('Sagent Pharmaceuticals','ibandronate sodium','qmzcvb',0),
	 ('Bryant Ranch Prepack','Bupropion Hydrochloride','vkbikw',0),
	 ('Actavis Elizabeth LLC','Metoclopramide','pnshpx',0),
	 ('Rite Aid Corporation','Avobenzone, Octisalate and Octocrylene','ggcclh',0),
	 ('REMEDYREPACK INC.','Glipizide','iafsdk',0),
	 ('Mei Shual Cosmetics Co., Ltd.','Titanium Dioxide, Zinc Oxide','nsanow',1),
	 ('L''Oreal USA Products Inc','Octinoxate and Titanium dioxide','pmjafw',0),
	 ('Aurobindo Pharma Limited','Lamivudine and Zidovudine','njeudr',1),
	 ('Avon Products, Inc.','Salicylic acid','vlkvbf',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Hyland''s','TOXICODENDRON RADICANS LEAF','xlvytd',0),
	 ('Deseret Biologicals, Inc.','Grindelia (Robusta), Urtica urens, Ledum palustre, Staphysagria, Cedron,','jkzqii',1),
	 ('STAT RX USA LLC','TIAGABINE HYDROCHLORIDE','uftnis',0),
	 ('Bare Escentuals Beauty Inc.','Titanium Dioxide and Zinc Oxide','hgjdxe',0),
	 ('Harrison Specialty Co., Inc.','ALCOHOL','vndmgh',1),
	 ('Ballay Pharmaceuticals, Inc','Acetaminophen','zjinzq',0),
	 ('Noven Therapeutics, LLC','estradiol','middpt',1),
	 ('Cadila Healthcare Limited','Tramadol Hydrochloride and Acetaminophen','yagnvu',0),
	 ('H E B','Acetaminophen, Diphenhydramine HCl','fjysli',0),
	 ('ALK-Abello, Inc.','Black Birch','awjnzw',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Apotex Corp.','Ramipril','itgiew',0),
	 ('Aphena Pharma Solutions - Tennessee, Inc.','Gemfibrozil','untkpu',0),
	 ('Apotheca Company','Rock rose,','xprted',1),
	 ('RITE AID CORPORATION','ETHYL ALCOHOL','dgfvyu',0),
	 ('School Health Corporation','Benzalkonium Chloride','eosgjw',1),
	 ('Physicians Total Care, Inc.','Lansoprazole','vtttaj',0),
	 ('Cardinal Health','IRBESARTAN AND HYDROCHLOROTHIAZIDE','zxriwr',1),
	 ('ERBAVIVA INC.','ZINC OXIDE','bckkxw',0),
	 ('A-S Medication Solutions LLC','ATAZANAVIR SULFATE','xlfuee',1),
	 ('Physicians Total Care, Inc.','LISINOPRIL AND HYDROCHLOROTHIAZIDE','jpctyv',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Stiefel Laboratories Inc','benzoyl peroxide','irzujx',1),
	 ('American Health Packaging','AMLODIPINE BESYLATE','fsnqsv',0),
	 ('Kingdom Animalia, LLC, DBA Hourglass Cosmetics','Zinc Oxide, Titanium Dioxide','kaicuh',0),
	 ('Mckesson Contract Packaging','Lisinopril','dmxusi',1),
	 ('St Marys Medical Park Pharmacy','Donepezil Hydrochloride','fiwzsw',0),
	 ('H E B','Menthol, methyl salicylate','aosziz',1),
	 ('Forces of Nature','CALENDULA OFFICINALIS FLOWERING TOP, GERANIUM MACULATUM ROOT, SODIUM CHLORIDE, and RANUNCULUS BULBOSUS','pbbzhv',0),
	 ('Beacon Promotions, Inc.','OCTINOXATE, OXYBENZONE','tlcjxl',1),
	 ('Alvogen, Inc.','nifedipine','ovycev',1),
	 ('Uriel Pharmacy Inc.','Anagallis Taraxacum','vbddkt',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Cardinal Health','MAGNESIUM SULFATE','ubyavo',1),
	 ('Nelco Laboratories, Inc.','Chaetomium globosum','sdsylq',0),
	 ('Golden State Medical Supply, Inc','venlafaxine hydrochloride','ftdpfm',1),
	 ('CIMA LABS INC','Cyclobenzaprine Hydrochloride','pavaot',1),
	 ('Family Dollar','Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride','kxsyen',0),
	 ('Mylan Pharmaceuticals Inc.','atovaquone and proguanil hydrochloride','vskplk',0),
	 ('Heel Inc','BLACK COHOSH and STRONTIUM CARBONATE and','onogkc',1),
	 ('NorthStar RxLLC','venlafaxine','qetzwv',1),
	 ('Universal Distribution Center LLC','White Petroleum','hxobly',0),
	 ('ALK-Abello, Inc.','Watermelon','liqgmi',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Costco Wholesale Company','Ranitidine','rknwty',0),
	 ('Physicians Total Care, Inc.','Torsemide','axijvz',0),
	 ('State of Florida DOH Central Pharmacy','SULINDAC','mawplz',0),
	 ('Conopco Inc. d/b/a Unilever','Aluminum Zirconium Tetrachlorohydrex GLY','ogpgtr',0),
	 ('CooperSurgical, Inc.','Iodine and Potassium Iodide','wantme',1),
	 ('The Magni Company','not applicable','vyyifq',0),
	 ('ViiV Healthcare Company','lamivudine','rvcdmt',1),
	 ('Taro Pharmaceuticals U.S.A., Inc.','Nystatin','gazgcw',1),
	 ('Bryant Ranch Prepack','Pantoprazole Sodium','lvgltg',0),
	 ('Blenheim Pharmacal, Inc.','Penicillin V Potassium','bsnrat',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Kinray','menthol topical analgesic','vsdrzs',1),
	 ('Octapharma Pharmazeutika Produktionsgesellschaft m.b.H.','Albumin Human','hfmfcn',0),
	 ('Procter & Gamble Manufacturing Company','Aluminum Zirconium Tetrachlorohydrex Gly','kaxmqz',1),
	 ('Insys Therapeutics, Inc.','FENTANYL','qcgprk',0),
	 ('H E B','Nicotine Polacrilex','nhkdri',0),
	 ('MedVantx, Inc.','Fluocinonide','bdixrb',0),
	 ('Atlantic Biologicals Corps','Midazolam Hydrochloride','mplhoo',1),
	 ('Washington Homeopathic Products','CAULOPHYLLUM THALICTROIDES ROOT','joozqs',1),
	 ('Preferred Pharmaceuticals, Inc','simethicone','iymief',0),
	 ('Humphreyline','Alcohol','aluibo',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Bryant Ranch Prepack','Trazodone Hydrochloride','fangjf',1),
	 ('Cadila Healthcare Limited','Lamotrigine','lwread',0),
	 ('Hyland''s','SODIUM PHOSPHATE, DIBASIC, ANHYDROUS','udjaug',1),
	 ('AvKARE, Inc.','Valacyclovir Hydrochloride','fzjzir',1),
	 ('Benefit Cosmetics, LLC','AVOBENZONE, OCTINOXATE, OCTISALATE','pnvdxw',0),
	 ('Nelco Laboratories, Inc.','Brazil Nut','toyazv',0),
	 ('Sun Pharmaceutical Industries Limited','TIAGABINE HYDROCHLORIDE','fersra',0),
	 ('Kaiser Foundation Hospitals','Bacitracin Zinc','nbwmge',0),
	 ('L Perrigo Company','cetirizine hydrochloride','csvdlu',0),
	 ('Galentic Pharma (India) Private Limited','bacitracin zinc, neomycin sulfate and polymyxin b sulfate','mrtwoq',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Taro Pharmaceuticals U.S.A., Inc.','Fluorouracil','lqbsqj',0),
	 ('Antigen Laboratories, Inc.','Grain Smut Mixture','jhlqlu',0),
	 ('UCB, Inc.','verapamil hydrochloride','ryvtri',0),
	 ('Torrent Pharmaceuticals Limited','LEVOFLOXACIN','xcommt',1),
	 ('Boehringer Ingelheim Pharmaceuticals, Inc.','simethicone','miwizs',1),
	 ('Cardinal Health','haloperidol','wnailo',0),
	 ('DESERET BIOLOGICALS, INC','LYCOPODIUM CLAVATUM, NATRUM MURIATICUM, SEPIA, BELLADONNA, CAUSTICUM, PHOSPHORUS, SULPHUR, 5-HYDROXYTRYPTOPHAN','btujyb',1),
	 ('Perrigo New York Inc.','imiquimod','oyggwj',0),
	 ('AMCOL Health and Beauty Solutions, Inc.','Homosalate, Octisalate, Octocrylene, Oxybenzone, Avobenzone','rpdxuf',1),
	 ('REMEDYREPACK INC.','Minocycline hydrochloride','ryukae',1);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Par Pharmaceutical Inc.','levetiracetam','uoqpqr',0),
	 ('Lake Erie Medical DBA Quality Care Products LLC','rizatriptan benzoate','qdpjvy',1),
	 ('MedVantx, Inc.','Ibuprofen','vbwcdu',0),
	 ('Mylan Pharmaceuticals Inc.','potassium chloride','ahyaxn',0),
	 ('Meijer Distribution, Inc','Sodium fluoride','iycjka',0),
	 ('Bioelements, Inc.','Salicylic Acid','yujjwj',1),
	 ('Major Pharmaceuticals','ACETAMINOPHEN','azimeg',0),
	 ('Nelco Laboratories, Inc.','Italian Rye Grass','gykxeh',1),
	 ('Allegis Pharmaceuticals, LLC','Brompheniramine Maleate, Phenylephrine Hydrochloride, and Dextromethorphan Hydrobromide','knwbzw',0),
	 ('Unit Dose Services','Bumetanide','xerrue',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('HOMEOLAB USA INC.','CIMICIFUGA RACEMOSA','uzhtli',0),
	 ('Roxane Laboratories, Inc.','Losartan Potassium','lixovl',0),
	 ('Unit Dose Services','Amitriptyline Hydrochloride','wngghp',1),
	 ('Ventura International LTD','Octinoxate, Octisalate, and Oxybenzone','lkusts',0),
	 ('Nelco Laboratories, Inc.','Burweed Marsh Elder','svcgvr',1),
	 ('Pfizer Laboratories Div Pfizer Inc.','Methotrexate','zxkhcu',1),
	 ('CVS Pharmacy','Ibuprofen','zkahft',1),
	 ('NCS HealthCare of KY, Inc dba Vangard Labs','oxybutynin chloride','yaslat',0),
	 ('Carilion Materials Management','vitamin/mineral supplement with magnesium carbonate, calcium carbonate and folic acid','vypxei',0),
	 ('Hospira, Inc.','SODIUM BICARBONATE','dpaqfy',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Seton Pharmaceuticals','Lidocaine Hydrochloride','ylzjoh',0),
	 ('Unither Manufacturing, LLC','methylphenidate hydrochloride','qnguev',1),
	 ('Glenmark Generics Inc., USA','Metformin Hydrochloride','qnbhik',0),
	 ('Jubilant HollisterStier LLC','Botrytis cinerea','fplxzb',0),
	 ('Glenmark Generics Inc., USA','montelukast sodium','dfmybt',1),
	 ('Natural Health Supply','CALCIUM CATION','jchqhw',0),
	 ('Rite Aid','Menthol, Zinc Oxide','rdiqih',0),
	 ('Covis Pharmaceuticals Inc','cefuroxime','edazmv',0),
	 ('Physicians Total Care, Inc.','Disulfiram','xradrp',1),
	 ('labora','droga','nose',0);
INSERT INTO public.drug (drug_lab,"name",active,active_percentage) VALUES
	 ('Cardinal Health','jeje','wcwtgk',1);
